version: "3.8"

services:
  app:
    container_name: twitter-visuals
    image: twitter-visuals
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
